import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "FlowdeX IA",
  description: "Automatización Inteligente",
  icons: {
    icon: '/favicon.ico',
  },
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 15618532eb7e866ae6ad5e8a889affbc87a59285
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="es">
=======
    <html lang="en">
>>>>>>> 15618532eb7e866ae6ad5e8a889affbc87a59285
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
<<<<<<< HEAD
}
=======
}
>>>>>>> 15618532eb7e866ae6ad5e8a889affbc87a59285
